db:
  dialect: 'sqlite:///'
  name: 'corona_analysis'
tables:
  # parent tables
  calendar_year: "_calendar_year"
  calendar_week: "_calendar_week"
  calendar_day: "_calendar_day"
  agegroup_05y: "_agegroup_05y"
  agegroup_10y: "_agegroup_10y"
  agegroup_rki: "_agegroup_rki"
  classification_icd10: "_classification_icd10"
  country: "_country"
  country_subdivision1: "_country_subdivision1"
  country_subdivision2: "_country_subdivision2"
  country_subdivision3: "_country_subdivision3"
  vaccine: "_vaccine"
  vaccine_series: "_vaccine_series"
  # population
  population_country: "population_country"
  population_country_agegroup: "population_country_agegroup"
  population_subdivision1: "population_subdivision1"
  population_subdivision2: "population_subdivision2"
  population_subdivision3: "population_subdivision3"
  life_expectancy: "life_expectancy"
  median_age: "median_age"
  # mortality
  mortality_weekly_agegroup: "mortality_weekly_agegroup"
  mortality_annual_agegroup_cause: "mortality_annual_agegroup_cause"
  # hospital
  hospital_annual: "hospital_annual"
  hospital_annual_staff: "hospital_annual_staff"
  # vaccination
  vaccination_daily: "vaccination_daily"
  vaccination_daily_manufacturer: "vaccination_daily_manufacturer"
  vaccination_daily_subdivision1: "vaccination_daily_subdivision1"