rki_covid_daily: 'https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data'
rki_tests_weekly: 'https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Testzahlen-gesamt.xlsx?__blob=publicationFile'
rki_tests_weekly_states: 'https://ars.rki.de/Docs/SARS_CoV2/Daten/data_wochenbericht.xlsx'
rki_rvalue_daily: 'https://raw.githubusercontent.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/main/Nowcast_R_aktuell.csv'
rki_vaccination_states: 'https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv'
rki_vaccination_rates: 'https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv'
rki_vaccinations_daily_cumulative: 'https://raw.githubusercontent.com/micb25/RKI_COVID19_DATA/master/Impfquotenmonitoring/RKI_COVID19_Impfquotenmonitoring.csv'
owid_vaccinations_daily: 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'
owid_vaccinations_daily_manufacturer: 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations-by-manufacturer.csv'
divi_itcu_daily_counties: 'https://diviexchange.blob.core.windows.net/%24web/zeitreihe-tagesdaten.csv'
divi_itcu_daily_states: 'https://diviexchange.blob.core.windows.net/%24web/zeitreihe-bundeslaender.csv'
owid_covid: 'https://covid.ourworldindata.org/data/owid-covid-data.csv'
estsat_weekly_deaths_agegroups: 'demo_r_mwk_10'
estsat_death_causes_annual_agegroups: 'hlth_cd_aro'
estat_population_agegroups: 'demo_pjangroup'
estat_population_nuts_2: 'demo_r_d2jan'
estat_life_expectancy: 'demo_mlexpec'
estat_population_structure_indicators: 'demo_pjanind'
genesis_hospitals_annual: '23111-0001'
genesis_hospital_staff_annual: '23111-0002'
genesis_population_subdivision_3: '12411-0015'