#source_description_frequency_specification1_specification2
#'specification' can be something like 'state' to determine that dataset is ordered by state
rki_covid_daily: 'https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data'
rki_test_weekly: 'https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Testzahlen-gesamt.xlsx?__blob=publicationFile'
rki_test_weekly_state: 'https://ars.rki.de/Docs/SARS_CoV2/Daten/data_wochenbericht.xlsx'
rki_rvalue_daily: 'https://raw.githubusercontent.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/main/Nowcast_R_aktuell.csv'
rki_vaccination_daily_state: 'https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv'
rki_vaccination_daily_rate: 'https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv'
rki_vaccination_daily_cumulative: 'https://raw.githubusercontent.com/micb25/RKI_COVID19_DATA/master/Impfquotenmonitoring/RKI_COVID19_Impfquotenmonitoring.csv'
owid_vaccination_daily: 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'
owid_vaccination_daily_manufacturer: 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations-by-manufacturer.csv'
divi_itcu_daily_countie: 'https://diviexchange.blob.core.windows.net/%24web/zeitreihe-tagesdaten.csv'
divi_itcu_daily_state: 'https://diviexchange.blob.core.windows.net/%24web/zeitreihe-bundeslaender.csv'
owid_covid_daily: 'https://covid.ourworldindata.org/data/owid-covid-data.csv'
estat_mortality_weekly_agegroup: 'demo_r_mwk_10'
estat_mortalityCause_annual_agegroup: 'hlth_cd_aro'
estat_population_annual_agegroup: 'demo_pjangroup'
estat_population_annual_nuts_2: 'demo_r_d2jan'
estat_lifeExpectancy_annual: 'demo_mlexpec'
estat_populationStructureIndicator_annual: 'demo_pjanind'
genesis_hospital_annual: '23111-0001'
genesis_hospitalStaff_annual: '23111-0002'
genesis_population_subdivision3: '12411-0015'