from_file:
  classifications_icd10:
    filename: "classifications_icd10.ftr"
    index_col: "icd10"
  countries:
    filename: "countries.ftr"
    index_col: "country_en"
  countries_subdivision1:
    filename: "countries_subdivision1.ftr"
    index_col: "nuts_1"
  countries_subdivision2:
    filename: "countries_subdivision2.ftr"
    index_col: "nuts_2"
  countries_subdivision3:
    filename: "countries_subdivision3.ftr"
    index_col: "nuts_3"
from_config:
  calendar_start_year: 1990
  calendar_end_year: 2050
  agegroups_05y:
    - "00-04"
    - "05-09"
    - "10-14"
    - "15-19"
    - "20-24"
    - "25-29"
    - "30-34"
    - "35-39"
    - "40-44"
    - "45-49"
    - "50-54"
    - "55-59"
    - "60-64"
    - "65-69"
    - "70-74"
    - "75-79"
  agegroups_10y:
    - "00-09"
    - "10-19"
    - "20-29"
    - "30-39"
    - "40-49"
    - "50-59"
    - "60-69"
    - "70-79"
  agegroups_rki:
    - "00-04" 
    - "05-14" 
    - "15-34" 
    - "35-59" 
    - "60-79"
  incidence_reference_year: 2020
  berlin_districts:
    11001: 11000
    11002: 11000
    11003: 11000
    11004: 11000
    11005: 11000
    11006: 11000
    11007: 11000
    11008: 11000
    11009: 11000
    11010: 11000
    11011: 11000
    11012: 11000
  vaccines:
    - Comirnaty:
        brand_name1: "Comirnaty"
        brand_name2: ""
        manufacturer: "Pfizer/BioNTech"
        vaccine_type: "mRNA"
    - Janssen:
        brand_name1: "Janssen"
        brand_name2: ""
        manufacturer: "Johnson&Johnson"
        vaccine_type: "Viral vector"
    - Spikevax:
        brand_name1: "Spikevax"
        brand_name2: ""
        manufacturer: "Moderna"
        vaccine_type: "mRNA"
    - Vaxzevria:
        brand_name1: "Vaxzevria"
        brand_name2: "Covishield"
        manufacturer: "Oxford/AstraZeneca"
        vaccine_type: "Viral vector"
    - Sputnik V:
        brand_name1: "Sputnik V"
        brand_name2: ""
        manufacturer: "Gamaleya Research Institute of Epidemiology"
        vaccine_type: "mRNA"
    - Sinopharm:
        brand_name1: "Sinopharm"
        brand_name2: ""
        manufacturer: "Beijing Institute of Biological Products"
        vaccine_type: "Inactivated"
    - Convidecia:
        brand_name1: "Convidecia"
        brand_name2: ""
        manufacturer: "CanSino Biologics"
        vaccine_type: "Viral vector"
    - Covaxin:
        brand_name1: "Covaxin"
        brand_name2: ""
        manufacturer: "Bharat Biotech"
        vaccine_type: "Inactivated"
    - CoronaVac:
        brand_name1: "CoronaVac"
        brand_name2: ""
        manufacturer: "Sinovac"
        vaccine_type: "Inactivated"
    - Nuvaxovid:
        brand_name1: "Nuvaxovid"
        brand_name2: "Covovax"
        manufacturer: "Novavax"
        vaccine_type: "Subunit"
    - Vidprevtyn:
        brand_name1: "Vidprevtyn"
        brand_name2: ""
        manufacturer: "Sanofi"
        vaccine_type: "Subunit"
  vaccine_series:
    1: "vaccinated"
    2: "fully vaccinated"
    3: "boostered"
    4: "boostered"
    5: "boostered"
    6: "boostered"