urls:
  rki_covid_daily: 'https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data'
  rki_tests_weekly: 'https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Testzahlen-gesamt.xlsx?__blob=publicationFile'
  rki_tests_weekly_states: 'https://ars.rki.de/Docs/SARS_CoV2/Daten/data_wochenbericht.xlsx'
  rki_rvalue_daily: 'https://raw.githubusercontent.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/main/Nowcast_R_aktuell.csv'
  rki_vaccination_states: 'https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv'
  rki_vaccination_rates: 'https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv'
  rki_vaccinations_daily_cumulative: 'https://raw.githubusercontent.com/micb25/RKI_COVID19_DATA/master/Impfquotenmonitoring/RKI_COVID19_Impfquotenmonitoring.csv'
  divi_itcu_daily_counties: 'https://diviexchange.blob.core.windows.net/%24web/zeitreihe-tagesdaten.csv'
  divi_itcu_daily_states: 'https://diviexchange.blob.core.windows.net/%24web/zeitreihe-bundeslaender.csv'
  owid_covid: 'https://covid.ourworldindata.org/data/owid-covid-data.csv'
estat_tables:
  estsat_weekly_deaths_agegroups: 'demo_r_mwk_10'
  estsat_death_causes_annual_agegroups: 'hlth_cd_aro'
  estat_population_agegroups: 'demo_pjangroup'
  estat_population_nuts_2: 'demo_r_d2jan'
  estat_life_expectancy: 'demo_mlexpec'
  estats_population_structure_indicators: 'demo_pjanind'
genesis_tables:
  hospitals_annual: '23111-0001'
  hospital_staff_annual: '23111-0002'
incidence_reference_year: 2020

# cols
rki_covid_daily:
  translation:
    FID: 'fid'
    IdBundesland: 'bundesland_id'
    Bundesland: 'subdivision_1'
    Landkreis: 'subdivision_2'
    Altersgruppe: 'rki_agegroups'
    Geschlecht: 'sex'
    AnzahlFall: 'amount_cases'
    AnzahlTodesfall: 'amount_deaths'
    Meldedatum: 'reporting_date'
    IdLandkreis: 'subdivision_2_id'
    Datenstand: 'data_date'
    NeuerFall: 'new_cases'
    NeuerTodesfall: 'new_deaths'
    Refdatum: 'reference_date'
    NeuGenesen: 'new_recovered'
    AnzahlGenesen: 'amount_recovered'
    IstErkrankungsbeginn: 'date_of_disease_onset'
    Altersgruppe2: 'rki_agegroups2'
  cols:
    fid: 'fid'
    bundesland_id: 'bundesland_id'
    subdivision_1: 'subdivision_1'
    subdivision_2: 'subdivision_2'
    rki_agegroups: 'rki_agegroups'
    sex: 'sex'
    amount_cases: 'amount_cases'
    amount_deaths: 'amount_deaths'
    reporting_date: 'reporting_date'
    subdivision_2_id: 'subdivision_2_id'
    data_date: 'data_date'
    new_cases: 'new_cases'
    new_deaths: 'new_deaths'
    reference_date: 'reference_date'
    new_recovered: 'new_recovered'
    amount_recovered: 'amount_recovered'
    date_of_disease_onset: 'date_of_disease_onset'
    rki_agegroups2: 'rki_agegroups2'
    geo: 'geo'
    iso_key: 'iso_key'
  agegroup_mapping:
    A00-A04: '00-04'
    A05-A14: '05-14'
    A15-A34: '15-34'
    A35-A59: '35-59'
    A60-A79: '60-79'
    A80+: '80+'
    unbekannt: 'UNK'
  berlin_district_mapping:
    11001: 11000
    11002: 11000
    11003: 11000
    11004: 11000
    11005: 11000
    11006: 11000
    11007: 11000
    11008: 11000
    11009: 11000
    11010: 11000
    11011: 11000
    11012: 11000
rki_tests_weekly:
  translation:
    Kalenderwoche: 'calendar_week'
    Anzahl Testungen: 'amount'
    Positiv getestet: 'positive'
    Positivenanteil (%): 'positive_percentage'
    Anzahl übermittelnder Labore: 'amount_transferring_laboratories'
  cols:
    calendar_week: 'calendar_week'
    amount: 'amount'
    positive: 'positive'
    positive_percentage: 'positive_percentage'
    amount_transferring_laboratories: 'amount_transferring_laboratories'
    iso_cw: 'iso_cw'
    iso_year: 'iso_year'
    is_key: 'iso_key'
    geo: 'geo'
rki_rvalue_daily:
  translation: 
    Datum: 'date'
    PS_COVID_Faelle: 'point_estimation_covid'
    UG_PI_COVID_Faelle: 'll_prediction_interval_covid'
    OG_PI_COVID_Faelle: 'ul_prediction_interval_covid'
    PS_COVID_Faelle_ma4: 'point_estimation_covid_smoothed'
    UG_PI_COVID_Faelle_ma4: 'll_prediction_interval_covid_smoothed'
    OG_PI_COVID_Faelle_ma4: 'ul_prediction_interval_covid_smoothed'
    PS_7_Tage_R_Wert: 'point_estimation_7_day_rvalue'
    UG_PI_7_Tage_R_Wert: 'll_prediction_interval_7_day_rvalue'
    OG_PI_7_Tage_R_Wert: 'ul_prediction_interval_7_day_rvalue'
  cols:
    date: 'date'
    point_estimation_covid: 'point_estimation_covid'
    ll_prediction_interval_covid: 'll_prediction_interval_covid'
    ul_prediction_interval_covid: 'ul_prediction_interval_covid'
    point_estimation_covid_smoothed: 'point_estimation_covid_smoothed'
    ll_prediction_interval_covid_smoothed: 'll_prediction_interval_covid_smoothed'
    ul_prediction_interval_covid_smoothed: 'ul_prediction_interval_covid_smoothed'
    point_estimation_7_day_rvalue: 'point_estimation_7_day_rvalue'
    ll_prediction_interval_7_day_rvalue: 'll_prediction_interval_7_day_rvalue'
    ul_prediction_interval_7_day_rvalue: 'ul_prediction_interval_7_day_rvalue'
    geo: 'geo'
rki_vaccinations_daily_cumulative:
  translation:
    timestamp: 'timestamp'
    ISODate: 'calendar_days'
    IdBundesland: 'bundesland_id'
    Bundesland: 'subdivision_1'
    Impfungenkumulativ: 'first_vaccination'
    DifferenzzumVortag: 'first_vaccination_delta'
    IndikationnachAlter: 'indication_by_age'
    BeruflicheIndikation: 'indication_by_profession'
    MedizinischeIndikation: 'indication_by_medical'
    PflegeheimbewohnerIn: 'nursing_home_resident'
    ZweiteImpfungkumulativ: 'second_vaccination'
    ZweiteImpfungDifferenzzumVortag: 'second_vaccination_delta'
    Auffrischimpfungen: 'booster_vaccination'
  cols:
    timestamp: 'timestamp'
    calendar_days: 'calendar_days'
    bundesland_id: 'bundesland_id'
    subdivision_1: 'subdivision_1'
    first_vaccination: 'first_vaccination'
    first_vaccination_delta: 'first_vaccination_delta'
    indication_by_age: 'indication_by_age'
    indication_by_profession: 'indication_by_profession'
    indication_by_medical: 'indication_by_medical'
    nursing_home_resident: 'nursing_home_resident'
    second_vaccination: 'second_vaccination'
    second_vaccination_delta: 'second_vaccination_delta'
    booster_vaccination: 'booster_vaccination'

rki_vaccinations_daily_states:
  translation:
    Impfdatum: 'date'
    BundeslandId_Impfort: 'subdivision_1_id'
    Impfstoff: 'vaccine'
    Impfserie: 'vaccine_series'
    Anzahl: 'amount'
  cols:
    date: 'date'
    subdivision_1_id: 'subdivision_1_id'
    vaccine: 'vaccine'
    vaccine_series: 'vaccine_series'
    amount: 'amount'